version: '3.9'

services:
  backend:
    container_name: Screenshot-to-Code-Backend
    restart: always
    build: 
      context: ./backend
      dockerfile: Dockerfile 
    networks:
      - stc_bridge
    env_file:
      - stack.env
    ports:
      - "${BACKEND_PORT:-7001}:${BACKEND_PORT:-7001}"
    command: poetry run uvicorn main:app --host 0.0.0.0 --port ${BACKEND_PORT:-7001}
  
  frontend:
    container_name: Screenshot-to-Code-Frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - stc_bridge
    env_file:
      - stack.env
    ports:
      - "5173:5173"

networks:
  stc_bridge:
    driver: bridge
    external: true
